<?php
    require ("MENU_PRINCIPAL.php");
?>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Presentación del Colegio Columna Pasco</title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
 <!-- SECCIÒN DE PRESENTACION -->
    <section class="presentacion">
        <h2>PRESENTACIÓN DEL COLEGIO COLUMNA PASCO</h2>
        <p>
            El Colegio Columna Pasco es una institución comprometida con la formación integral de sus estudiantes, promoviendo valores y excelencia académica. Nos enorgullecemos de ofrecer una educación de calidad que prepara a nuestros alumnos para los desafíos del futuro.
        </p>
        <p>
            A lo largo de los años, hemos implementado una serie de programas innovadores que buscan no solo formar estudiantes académicamente competentes, sino también ciudadanos responsables y conscientes de su rol en la sociedad. Nuestro enfoque educativo se basa en la colaboración y el respeto.
        </p>
        <p>
            Invitamos a la comunidad educativa y a las familias a ser parte activa de este proceso de formación, trabajando juntos para garantizar el éxito de cada uno de nuestros estudiantes y hacer de nuestro colegio un espacio de crecimiento y aprendizaje continuo.
        </p>
        <p>
          Ubicado en el corazón de San Juan Pampa, en la próspera provincia de Yanacancha, el Colegio N°35756 Columna Pasco se enorgullece de ofrecer una educación de alta calidad, respaldada por la UGEL PASCO y bajo la supervisión de la Dirección Regional de Educación (DRE PASCO). Nuestra institución educativa no solo forma estudiantes, sino que forja líderes con una sólida base académica, moral y emocional, listos para enfrentar los desafíos de un mundo moderno y en constante cambio.
        </p>
        <p class="direc">
          EL DIRECTOR.
        </p>
    </section>
<!-- SECCION DE CUADROS -->
    <section class="seccion">
        <h2>¿PORQUÉ ELEGIR AL COLEGIO COLUMNA PASCO?</h2>
        <div class="cuadros">
            <div class="cuadro titulo1">
                <h3>Formación Integral y de Calidad</h3>
                <img src="img/calidad.png">
            </div>
            <div class="cuadro titulo2">
                <h3>Desarrollo de Habilidades para el Futuro</h3>
                <img src="img/habilidad.png" >
            </div>
            <div class="cuadro titulo3">
                <h3>Entorno Seguro y Metodología Innovadora</h3>
                <img src="img/entorno-seguro.png" >
            </div>
        </div>
    </section>

<!-- NUESTRA CIFRAS -->
    <section class="nuestras-cifras">
        <h2>- Columna Pasco - </h2>
        <h3>NUESTRAS CIFRAS</h3>
        <div class="cuadros1">
            <div class="cuadro1 cuadro1">
                  <h4>Docentes</h4>
                <p>28</p>
            </div>
            <div class="cuadro1 cuadro2">
                <h4>Estudiantes</h4>
                <p>690</p>
            </div>
        </div>
    </section>

<!--PIE DE PAGINA-->
    <footer class="boby_pie">
        <div class="contai_pie">
            <div class="footer_content">
                <h4>Visitanos:</h4>
                <p><strong>HOTMAIL:</strong> instedu_columnapasco@hotmail.com</p>
                <p><strong>DIRECCIÒN:</strong>  Av. Paseo de Los Vecendores,Cerro De Pasco-19001</p>
            </div>
            <div class="footer_content">
                <h4>Menú</h4>
                 <ul class="list">
                    <li><a href="INICIO.php">Inicio</a></li>
                    <li><a href="DATOS_INFORMATIVOS.php">¿Quienes Somos?</a></li>
                    <li><a href="ESTUDIANTES.php">Comunidad Educativa</a></li>
                    <li><a href="NOTICIAS.php">Noticias</a></li>
                    <li><a href="CONTACTANOS.php">Contáctanos</a></</li>
                 </ul>
            </div>
            <div class="footer_content">
                <h4>Síguenos:</h4>
                <div class="social-links">
                    <a href="https://www.facebook.com/columnapasco40/?locale=es_ES"><i class="fab fa-facebook-f"></i></a>
                    <a href="https://www.tiktok.com/discover/columna-pasco-colegio"><i class="fab fa-tiktok"></i></a>
                </div>
            </div>
        </div>
        <div class="bottom_bar">
            <p>&copy; 2024 Todos los Derechos Reservados - I.E. "Columna Pasco"</p>
        </div>
    </footer>
</body>
</html>